const projects = [
  {
    id: 1,
    title: "EpiAI – Epilepsy Detection System",
    description: "AI system for epilepsy detection using EEG and Bi-directional CNN-LSTM model. Includes hospital dashboard for patient management.",
    period: "Oct 2024 – Present",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=800&h=400",
    categories: ["ai", "ml"],
    tags: ["EEG", "Bi-CNN-LSTM", "Medical AI"],
  },
  {
    id: 2,
    title: "Bright Brain – AI Educational Platform",
    description: "Interactive platform for children with AI-generated stories, games, and GPT narration.",
    period: "May 2025 – Present",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&h=400",
    categories: ["ai"],
    tags: ["GPT", "Text-to-Speech", "React"],
  },
  {
    id: 3,
    title: "Brain Stroke Prediction System",
    description: "Deep learning model for early stroke detection using medical report data (heartbeat, pressure, etc.).",
    period: "Apr 2025 – June 2025",
    image: "https://images.unsplash.com/photo-1603398938378-3dd4b9a54b83?auto=format&fit=crop&w=800&h=400",
    categories: ["ml"],
    tags: ["Medical AI", "Deep Learning", "Stroke Prediction"],
  },
  {
    id: 4,
    title: "Drug-Target Interaction Classifier",
    description: "ML/DL models for classifying drug-protein interaction using molecular fingerprints and sequences.",
    period: "Oct 2023 – Feb 2024",
    image: "https://images.unsplash.com/photo-1588776814546-2d547b2f60b5?auto=format&fit=crop&w=800&h=400",
    categories: ["ml"],
    tags: ["Bioinformatics", "Classification", "Drug Discovery"],
  },
  {
    id: 5,
    title: "Food Ingredients Forecasting",
    description: "Forecast food ingredient needs for restaurants using real datasets and time series analysis.",
    period: "Jul 2023 – Nov 2023",
    image: "https://images.unsplash.com/photo-1512058564366-c9e3c8e57f56?auto=format&fit=crop&w=800&h=400",
    categories: ["ml"],
    tags: ["Forecasting", "Time Series", "Data Analysis"],
  },
  {
    id: 6,
    title: "Horse Detection & Tracking System",
    description: "YOLOv7 model for detecting and tracking horses during races in real time.",
    period: "Jul 2023 – Dec 2023",
    image: "https://images.unsplash.com/photo-1553284966-19b8815c7817?auto=format&fit=crop&w=800&h=400",
    categories: ["cv"],
    tags: ["YOLOv7", "Object Detection", "Real-time AI"],
  },
  {
    id: 7,
    title: "Human Heartbeat Recognition",
    description: "Classify ECG signals using LightGBM for accurate heartbeat detection.",
    period: "Dec 2022 – May 2023",
    image: "https://images.unsplash.com/photo-1603395295302-c99f9283c438?auto=format&fit=crop&w=800&h=400",
    categories: ["ml"],
    tags: ["ECG", "LightGBM", "Signal Classification"],
  },
  {
    id: 8,
    title: "Crime Rate Prediction Model",
    description: "Time series LSTM model to forecast crime rates and types based on Chicago data.",
    period: "May 2023 – June 2024",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&h=400",
    categories: ["ml"],
    tags: ["LSTM", "Time Series", "Crime Prediction"],
  },
  {
    id: 9,
    title: "Self-Driving Car System",
    description: "YOLOv7 object detection and multi-task learning for traffic lights and signs on Riyadh streets.",
    period: "Mar 2022 – Nov 2022",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&h=400",
    categories: ["cv"],
    tags: ["YOLOv7", "Autonomous Driving", "Multi-task Learning"],
  },
  {
    id: 10,
    title: "COVID-19 Detection from CT Scans",
    description: "Transfer learning model with 99.6% accuracy using chest CT scan images.",
    period: "Mar 2022 – Jun 2022",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?auto=format&fit=crop&w=800&h=400",
    categories: ["cv", "ml"],
    tags: ["Medical Imaging", "Transfer Learning", "99.6% Accuracy"],
  },
  {
    id: 11,
    title: "Signature Verification System",
    description: "Academic research and model design for verifying handwritten signatures using deep learning.",
    period: "Jan 2022 – Mar 2022",
    image: "https://images.unsplash.com/photo-1588776814546-2d547b2f60b5?auto=format&fit=crop&w=800&h=400",
    categories: ["ml"],
    tags: ["Signature Recognition", "DL Research"],
  },
  {
    id: 12,
    title: "Deepfake Detection System",
    description: "98% accurate classifier using MISO model to detect deepfake videos from Kaggle dataset.",
    period: "Sep 2021 – Nov 2021",
    image: "https://images.unsplash.com/photo-1608746822660-21a55bdf2a59?auto=format&fit=crop&w=800&h=400",
    categories: ["cv", "ai"],
    tags: ["Deepfake", "Video Classification", "MISO Model"],
  },
];
